id: P009411
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:37:28.416601
source_metadata:
  id: bdr:W8LS20543
  title: སྲིད་པའི་གླུ་ཤགས།
  author: ''
  volumes:
    0a90b772340e4db2b15b52f10c3635ec:
      image_group_id: I8LS20545
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
