id: P009411
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20543
  title: སྲིད་པའི་གླུ་ཤགས།
  author: ''
  volumes:
    0a90b772340e4db2b15b52f10c3635ec:
      image_group_id: I8LS20545
      title: ''
      volume_number: 1
      total_pages: 276
