id: I4474E727
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T20:14:30+00:00'
last_modified: '2022-06-08T10:50:44.114253+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20543
  title: སྲིད་པའི་གླུ་ཤགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    3E96:
      image_group_id: I8LS20545
      title: ''
      total_pages: 276
      order: 1
      base_file: 3E96.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
